apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

configMapGenerator:
- name: test99-config
  literals:
    - SERVICE_PORT=80
    - DATABASE_HOST=localhost
    - DATABASE_PORT=5432

commonLabels:
  app: test99
